Rails.application.routes.draw do
  resources :categories

  root 'search#index'
  devise_for :users # routes are generated by the device gem
  get '/search', to: 'search#index', as: 'search'
  
  resources :pois
end
